# Starting dockerfile
FROM ubuntu

RUN apt-get update
RUN apt-get install gcc -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install g++ -y
RUN apt-get install python -y
RUN apt-get install python3 -y

EXPOSE 80

COPY main.py main.py

ENV NAME World

CMD [main.py]